export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_LIST_NEARBY_REQUEST = 'PRODUCT_LIST_NEARBY_REQUEST'
export const PRODUCT_LIST_NEARBY_SUCCESS = 'PRODUCT_LIST_NEARBY_SUCCESS'
export const PRODUCT_LIST_NEARBY_FAIL = 'PRODUCT_LIST_NEARBY_FAIL'
