export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_LIST_NEARBY_REQUEST = 'PRODUCT_LIST_NEARBY_REQUEST'
export const PRODUCT_LIST_NEARBY_SUCCESS = 'PRODUCT_LIST_NEARBY_SUCCESS'
export const PRODUCT_LIST_NEARBY_FAIL = 'PRODUCT_LIST_NEARBY_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_details_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_details_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_details_FAIL'

export const SELLER_DETAILS_REQUEST = 'SELLER_DETAILS_REQUEST'
export const SELLER_DETAILS_SUCCESS = 'SELLER_DETAILS_SUCCESS'
export const SELLER_DETAILS_FAIL = 'SELLER_DETAILS_FAIL'

export const PRODUCT_LIST_MY_REQUEST = 'PRODUCT_LIST_MY_REQUEST'
export const PRODUCT_LIST_MY_SUCCESS = 'PRODUCT_LIST_MY_SUCCESS'
export const PRODUCT_LIST_MY_FAIL = 'PRODUCT_LIST_MY_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'
